version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${PORT}:${PORT}"
        env_file:
            - .env
        volumes:
            - .env:/app/.env
        restart: always
